sudo: false
language: ruby
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.5
  - 2.3.1
before_install: gem install bundler -v 1.12.5
script:
  - bundle exec rake test
  - bundle exec rake rubocop
cache: bundler
deploy:
  provider: rubygems
  api_key: "$RUBYGEMS_API_KEY"
  on:
    tags: true
